/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ACCEPTANCE BAR for z23-fleet-gateway (tools/fleet_gateway.c).
 *
 * The loopback Streamable-HTTP front for the steering verbs: healthz,
 * initialize negotiation, tools/list, and tools/call dispatch into the
 * TESTED node binary. Written against an isolated state root and an
 * ephemeral loopback port; the gateway child is spawned by fork/exec and
 * reaped here. No case touches the network beyond loopback, the wallet,
 * deployment, or soak paths. POSIX only: on Windows the gateway refuses
 * and this group notes that instead. Do not edit this file to make the
 * implementation pass.
 */

#include "test/test_core.h"

#include "command/native_command.h"
#include "config/command_catalog.h"
#include "json/json.h"
#include "kernel/command_registry.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#if defined(_WIN32)
int test_fleet_gateway(void);
int test_fleet_gateway(void)
{
    printf("fleet_gateway: POSIX-only gateway, noting Windows refusal\n");
    return 0;
}
#else
#include <arpa/inet.h>
#include <netinet/in.h>
#include <signal.h>
#include <stdbool.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

#define GW_TEST_BIN_DEFAULT "build/bin/z23-fleet-gateway"
#define GW_TEST_NODE_DEFAULT "build/bin/z23"
#define GW_TEST_CAP (256u * 1024u)

static pid_t g_gw_pid = -1;
static int g_gw_port = -1;

/* Read one line (no newline) from fd. False on EOF/error/overflow. */
static bool gw_read_line(int fd, char *out, size_t cap)
{
    size_t n = 0;
    while (n + 1 < cap) {
        char c;
        ssize_t r = read(fd, &c, 1);
        if (r <= 0)
            return false;
        if (c == '\n')
            break;
        if (c != '\r')
            out[n++] = c;
    }
    out[n] = '\0';
    return true;
}

/* Spawn the gateway; parse its `ready port=N` line. True when serving. */
static bool gw_spawn(const char *bin, const char *node, const char *state)
{
    int fds[2];
    char line[256];
    if (pipe(fds) != 0)
        return false;
    g_gw_pid = fork();
    if (g_gw_pid < 0) {
        close(fds[0]);
        close(fds[1]);
        return false;
    }
    if (g_gw_pid == 0) {
        char *const argv[] = {(char *)bin, NULL};
        dup2(fds[1], STDOUT_FILENO);
        close(fds[0]);
        close(fds[1]);
        setenv("FLEET_GW_PORT", "0", 1);
        setenv("FLEET_GW_NODE", node, 1);
        setenv("XDG_STATE_HOME", state, 1);
        execv(bin, argv);
        _exit(127);
    }
    close(fds[1]);
    if (!gw_read_line(fds[0], line, sizeof(line))) {
        close(fds[0]);
        return false;
    }
    close(fds[0]);
    if (sscanf(line, "ready port=%d", &g_gw_port) != 1 || g_gw_port <= 0)
        return false;
    return true;
}

static void gw_stop(void)
{
    int st = 0;
    if (g_gw_pid < 0)
        return;
    kill(g_gw_pid, SIGTERM);
    waitpid(g_gw_pid, &st, 0);
    g_gw_pid = -1;
    g_gw_port = -1;
}

/* One HTTP exchange over loopback. Returns the body (after the blank
 * line) malloc'd, with the status code out. NULL on transport failure. */
static char *gw_exchange(const char *request, int *status)
{
    int fd;
    struct sockaddr_in v4;
    char *buf, *body;
    size_t cap = GW_TEST_CAP, n = 0;
    ssize_t r;
    *status = 0;
    fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0)
        return NULL;
    memset(&v4, 0, sizeof(v4));
    v4.sin_family = AF_INET;
    v4.sin_port = htons((uint16_t)g_gw_port);
    v4.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    if (connect(fd, (struct sockaddr *)&v4, sizeof(v4)) != 0) {
        close(fd);
        return NULL;
    }
    {
        size_t left = strlen(request), off = 0;
        while (left > 0) {
            r = write(fd, request + off, left);
            if (r <= 0) {
                close(fd);
                return NULL;
            }
            off += (size_t)r;
            left -= (size_t)r;
        }
    }
    buf = malloc(cap);
    if (!buf) {
        close(fd);
        return NULL;
    }
    for (;;) {
        if (n + 4096 >= cap) {
            close(fd);
            free(buf);
            return NULL;
        }
        r = read(fd, buf + n, cap - n - 1);
        if (r == 0)
            break;
        if (r < 0) {
            close(fd);
            free(buf);
            return NULL;
        }
        n += (size_t)r;
    }
    close(fd);
    buf[n] = '\0';
    if (sscanf(buf, "HTTP/1.1 %d", status) != 1) {
        free(buf);
        return NULL;
    }
    body = strstr(buf, "\r\n\r\n");
    if (!body) {
        free(buf);
        return NULL;
    }
    body += 4;
    {
        size_t blen = n - (size_t)(body - buf);
        char *out = malloc(blen + 1);
        if (!out) {
            free(buf);
            return NULL;
        }
        memcpy(out, body, blen);
        out[blen] = '\0';
        free(buf);
        return out;
    }
}

static char *gw_post(const char *path, const char *json, int *status)
{
    char req[GW_TEST_CAP];
    int n = snprintf(req, sizeof(req),
                     "POST %s HTTP/1.1\r\nHost: x\r\nContent-Type: "
                     "application/json\r\nContent-Length: %zu\r\n"
                     "Connection: close\r\n\r\n%s",
                     path, strlen(json), json);
    if (n <= 0 || (size_t)n >= sizeof(req))
        return NULL;
    return gw_exchange(req, status);
}

static char *gw_post_auth(const char *path, const char *json,
                         const char *bearer, int *status)
{
    char req[GW_TEST_CAP];
    int n;
    if (bearer)
        n = snprintf(req, sizeof(req),
                     "POST %s HTTP/1.1\r\nHost: x\r\nContent-Type: "
                     "application/json\r\nAuthorization: Bearer %s\r\n"
                     "Content-Length: %zu\r\n"
                     "Connection: close\r\n\r\n%s",
                     path, bearer, strlen(json), json);
    else
        n = snprintf(req, sizeof(req),
                     "POST %s HTTP/1.1\r\nHost: x\r\nContent-Type: "
                     "application/json\r\n"
                     "Content-Length: %zu\r\n"
                     "Connection: close\r\n\r\n%s",
                     path, strlen(json), json);
    if (n <= 0 || (size_t)n >= sizeof(req))
        return NULL;
    return gw_exchange(req, status);
}

static char *gw_get(const char *path, int *status)
{
    char req[512];
    int n = snprintf(req, sizeof(req),
                     "GET %s HTTP/1.1\r\nHost: x\r\nConnection: close\r\n\r\n",
                     path);
    if (n <= 0 || (size_t)n >= sizeof(req))
        return NULL;
    return gw_exchange(req, status);
}

static bool gw_body_has(const char *body, const char *needle)
{
    return body && needle && strstr(body, needle) != NULL;
}

/* Run the node CLI: <node> fleet steer <verb> --input=<json>. Captured
 * stdout malloc'd; NULL on any failure. No shell. */
static char *gw_node_run(const char *node, const char *verb, const char *in)
{
    int fds[2];
    pid_t pid;
    char arg[8192];
    char *out = NULL;
    size_t cap = 65536, n = 0;
    int sn = snprintf(arg, sizeof(arg), "--input=%s", in);
    if (sn <= 0 || (size_t)sn >= sizeof(arg))
        return NULL;
    if (pipe(fds) != 0)
        return NULL;
    pid = fork();
    if (pid < 0) {
        close(fds[0]);
        close(fds[1]);
        return NULL;
    }
    if (pid == 0) {
        char *const argv[] = {(char *)node, (char *)"fleet",
                              (char *)"steer", (char *)verb, arg, NULL};
        dup2(fds[1], STDOUT_FILENO);
        close(fds[0]);
        close(fds[1]);
        execv(node, argv);
        _exit(127);
    }
    close(fds[1]);
    out = malloc(cap);
    if (!out) {
        close(fds[0]);
        waitpid(pid, NULL, 0);
        return NULL;
    }
    for (;;) {
        ssize_t r;
        if (n + 4096 >= cap)
            break;
        r = read(fds[0], out + n, cap - n - 1);
        if (r <= 0)
            break;
        n += (size_t)r;
    }
    close(fds[0]);
    waitpid(pid, NULL, 0);
    if (n == 0) {
        free(out);
        return NULL;
    }
    out[n] = '\0';
    return out;
}

/* Mint a steering grant through the node CLI; copies the 32-hex id out. */
static bool gw_mint(const char *node, const char *scopes, char *id_out)
{
    char in[256];
    char *reply;
    const char *p;
    int sn = snprintf(in, sizeof(in),
                      "{\"action\":\"mint\",\"scopes\":\"%s\"}", scopes);
    if (sn <= 0 || (size_t)sn >= sizeof(in))
        return false;
    reply = gw_node_run(node, "grant", in);
    if (!reply)
        return false;
    p = strstr(reply, "\"id\":\"");
    if (!p || strlen(p + 6) < 32) {
        free(reply);
        return false;
    }
    memcpy(id_out, p + 6, 32);
    id_out[32] = '\0';
    free(reply);
    return true;
}

static const char *gw_bin(const char *env, const char *dflt)
{
    const char *v = getenv(env);
    return v && v[0] ? v : dflt;
}

/* First mail seq out of an escaped send body (\"seq\":N). -1 when absent. */
static long long gw_body_seq(const char *body)
{
    const char *p = body ? strstr(body, "\\\"seq\\\":") : NULL;
    char *end = NULL;
    long long s;
    if (!p)
        return -1;
    s = strtoll(p + 8, &end, 10);
    if (end == p + 8 || s < 0)
        return -1;
    return s;
}

/* Receiver-side ack through the real mail leaf, in-process (receivers act
 * locally; the gateway only ever reads). The mail CLI leaf is compat-only,
 * so fork/exec cannot ack: same pattern as the steer group's fmx_ack. */
static bool gw_mail_ack(const char *agent, long long cursor)
{
    struct json_value input;
    struct zcl_command_request request;
    struct zcl_command_reply reply;
    bool ok;
    json_init(&input);
    json_set_object(&input);
    memset(&request, 0, sizeof(request));
    request.input = &input;
    request.spec =
        zcl_command_registry_find(zcl_command_catalog(), "dev.agent.mail",
                                  NULL);
    zcl_command_reply_init(&reply, "zcl.agent_mail.v1");
    (void)json_push_kv_str(&input, "action", "ack");
    (void)json_push_kv_str(&input, "agent", agent);
    (void)json_push_kv_int(&input, "cursor", cursor);
    zcl_native_handle_dev_agent_mail(&request, &reply);
    ok = reply.status == ZCL_COMMAND_STATUS_PASSED;
    zcl_command_reply_free(&reply);
    json_free(&input);
    return ok;
}

static int gw_t_routes(void)
{
    int failures = 0;
    TEST("gateway: healthz, 404 and POST-only steer") {
        int st = 0;
        char *b = gw_get("/healthz", &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 200);
        ASSERT(gw_body_has(b, "\"ok\":true"));
        free(b);
        b = gw_get("/nope", &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 404);
        free(b);
        b = gw_get("/steer", &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 405);
        free(b);
        PASS();
    }
_test_next:;
    return failures;
}

static int gw_t_handshake(void)
{
    int failures = 0;
    TEST("gateway: initialize negotiates, tools list the verbs") {
        int st = 0;
        char *b = gw_post("/steer",
                          "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":"
                          "\"initialize\",\"params\":{\"protocolVersion\":"
                          "\"2025-06-18\"}}",
                          &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 200);
        ASSERT(gw_body_has(b, "\"protocolVersion\":\"2025-06-18\""));
        ASSERT(gw_body_has(b, "z23-fleet-gateway"));
        free(b);
        b = gw_post("/steer",
                    "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/list\"}",
                    &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"name\":\"steer_brief\""));
        ASSERT(gw_body_has(b, "\"name\":\"steer_send\""));
        ASSERT(gw_body_has(b, "\"name\":\"steer_evidence\""));
        free(b);
        b = gw_post("/steer",
                    "{\"jsonrpc\":\"2.0\",\"id\":3,\"method\":\"nope\"}",
                    &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"code\":-32601"));
        free(b);
        b = gw_post("/steer", "{oops", &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"code\":-32700"));
        free(b);
        PASS();
    }
_test_next:;
    return failures;
}

static int gw_t_calls(void)
{
    int failures = 0;
    TEST("gateway: brief, send, duplicate and refusal round-trip") {
        const char *node = gw_bin("Z23_TEST_NODE_BIN", GW_TEST_NODE_DEFAULT);
        char gid[64];
        char args[512];
        char *b;
        int st = 0, sn;
        ASSERT(gw_mint(node, "brief,send,evidence", gid));
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":10,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_brief\","
                      "\"arguments\":{\"grant\":\"%s\"}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "agents"));
        free(b);
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":11,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_send\","
                      "\"arguments\":{\"grant\":\"%s\",\"items\":[{\"to\":"
                      "\"gw-agent\",\"body\":\"probe\",\"ref\":\"gw-1\","
                      "\"idempotency_key\":\"gw-k1\"}]}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "queued"));
        ASSERT(!gw_body_has(b, "duplicate\\\":true"));
        free(b);
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "duplicate\\\":true"));
        free(b);
        /* Same key, changed payload: refused, never a duplicate. */
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":12,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_send\","
                      "\"arguments\":{\"grant\":\"%s\",\"items\":[{\"to\":"
                      "\"gw-agent\",\"body\":\"changed\",\"ref\":\"gw-1\","
                      "\"idempotency_key\":\"gw-k1\"}]}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "refused"));
        ASSERT(gw_body_has(b, "IDEMPOTENCY_CONFLICT"));
        ASSERT(!gw_body_has(b, "duplicate\\\":true"));
        free(b);
        /* Evidence before the receiver ack: delivered, not acknowledged. */
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":13,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_evidence\","
                      "\"arguments\":{\"grant\":\"%s\",\"type\":\"mail\","
                      "\"ref\":\"gw-1\"}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "delivered"));
        ASSERT(!gw_body_has(b, "acknowledged"));
        free(b);
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":14,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_send\","
                      "\"arguments\":{\"grant\":\"%s\",\"items\":[{\"to\":"
                      "\"gw-agent\",\"body\":\"probe\",\"ref\":\"gw-1\","
                      "\"idempotency_key\":\"gw-k1\"}]}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        {
            long long seq = gw_body_seq(b);
            ASSERT(seq > 0);
            ASSERT(gw_mail_ack("gw-agent", seq));
        }
        free(b);
        /* Evidence after the receiver ack: the gateway reports it. */
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":15,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_evidence\","
                      "\"arguments\":{\"grant\":\"%s\",\"type\":\"mail\","
                      "\"ref\":\"gw-1\"}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "acknowledged"));
        free(b);
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":16,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_send\","
                      "\"arguments\":{\"grant\":\"00000000000000000000000000"
                      "00000000\",\"items\":[{\"to\":\"gw-agent\",\"body\":"
                      "\"x\",\"ref\":\"gw-1\",\"idempotency_key\":"
                      "\"gw-k9\"}]}}}");
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":true"));
        ASSERT(gw_body_has(b, "STEER_GRANT_UNKNOWN"));
        free(b);
        PASS();
    }
_test_next:;
    return failures;
}

static int gw_t_auth(void);

int test_fleet_gateway(void);
int test_fleet_gateway(void)
{
    int failures = 0;
    const char *bin = gw_bin("Z23_TEST_GATEWAY_BIN", GW_TEST_BIN_DEFAULT);
    const char *node = gw_bin("Z23_TEST_NODE_BIN", GW_TEST_NODE_DEFAULT);
    char state[512];
    const char *saved_xdg = getenv("XDG_STATE_HOME");
    char saved[4096];
    bool had_xdg = saved_xdg != NULL;
    test_make_tmpdir(state, sizeof(state), "fleet_gateway", "iso");
    if (strlen(state) + 8 >= sizeof(state))
        return 1;
    strcat(state, "/state");
    if (mkdir(state, 0700) != 0)
        return 1;
    /* The direct node runs (grant mint) must land in the same isolated
     * store the gateway child serves; save and restore the ambient root. */
    if (had_xdg) {
        if (snprintf(saved, sizeof(saved), "%s", saved_xdg) < 0)
            return 1;
    }
    if (setenv("XDG_STATE_HOME", state, 1) != 0)
        return 1;
    if (!gw_spawn(bin, node, state)) {
        if (had_xdg)
            setenv("XDG_STATE_HOME", saved, 1);
        else
            unsetenv("XDG_STATE_HOME");
        return 1;
    }
    failures += gw_t_routes();
    failures += gw_t_handshake();
    failures += gw_t_calls();
    failures += gw_t_auth();
    /* No ASSERT lives here; the stop always runs on fall-through. */
    gw_stop();
    if (had_xdg)
        setenv("XDG_STATE_HOME", saved, 1);
    else
        unsetenv("XDG_STATE_HOME");
    if (failures == 0)
        printf("test_fleet_gateway: all passed\n");
    else
        printf("test_fleet_gateway: %d FAILED\n", failures);
    return failures;
}

static int gw_t_auth(void)
{
    int failures = 0;
    TEST("gateway: tool calls fail closed without exactly one grant") {
        const char *node = gw_bin("Z23_TEST_NODE_BIN", GW_TEST_NODE_DEFAULT);
        char gid[64];
        char args[512];
        char *b;
        int st = 0, sn;
        ASSERT(gw_mint(node, "brief,send,evidence", gid));
        /* No credential anywhere: refused before the node is forked. */
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":20,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":"
                         "\"steer_brief\",\"arguments\":{}}}",
                         NULL, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"code\":-32001"));
        ASSERT(gw_body_has(b, "grant required"));
        free(b);
        /* Header credential alone: carried to the node, brief succeeds. */
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":21,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":"
                         "\"steer_brief\",\"arguments\":{}}}",
                         gid, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "agents"));
        free(b);
        /* Header and argument agreeing: accepted. */
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":22,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_brief\","
                      "\"arguments\":{\"grant\":\"%s\"}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post_auth("/steer", args, gid, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        free(b);
        /* Header and argument differing: refused as ambiguous. */
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":23,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_brief\","
                      "\"arguments\":{\"grant\":\"00000000000000000000000000"
                      "00000000\"}}}");
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post_auth("/steer", args, gid, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"code\":-32002"));
        ASSERT(gw_body_has(b, "conflicting grants"));
        free(b);
        /* Non-token bytes in the header: refused, never forwarded. */
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":24,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":"
                         "\"steer_brief\",\"arguments\":{}}}",
                         "\",\"x\":1,//", &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"code\":-32002"));
        ASSERT(gw_body_has(b, "bad grant credential"));
        free(b);
        /* Unknown header credential: the node itself refuses it. */
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":25,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":"
                         "\"steer_brief\",\"arguments\":{}}}",
                         "00000000000000000000000000000000", &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":true"));
        ASSERT(gw_body_has(b, "STEER_GRANT_UNKNOWN"));
        free(b);
        PASS();
    }
_test_next:;
    return failures;
}
#endif /* _WIN32 */
