/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ACCEPTANCE BAR for z23-fleet-gateway (tools/fleet_gateway.c).
 *
 * The loopback Streamable-HTTP front for the steering verbs: healthz,
 * initialize negotiation, tools/list, and tools/call dispatch into the
 * TESTED node binary. Written against an isolated state root and an
 * ephemeral loopback port; the gateway child is spawned by fork/exec and
 * reaped here. No case touches the network beyond loopback, the wallet,
 * deployment, or soak paths. POSIX only: on Windows the gateway refuses
 * and this group notes that instead. Do not edit this file to make the
 * implementation pass.
 */

#include "test/test_core.h"

#include "command/native_command.h"
#include "config/command_catalog.h"
#include "json/json.h"
#include "kernel/command_registry.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#if defined(_WIN32)
int test_fleet_gateway(void);
int test_fleet_gateway(void)
{
    printf("fleet_gateway: POSIX-only gateway, noting Windows refusal\n");
    return 0;
}
#else
#include <arpa/inet.h>
#include <netinet/in.h>
#include <signal.h>
#include <stdbool.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
#include <errno.h>

#define GW_TEST_BIN_DEFAULT "build/bin/z23-fleet-gateway"
#define GW_TEST_NODE_DEFAULT "build/bin/z23"
#define GW_TEST_CAP (256u * 1024u)

static pid_t g_gw_pid = -1;
static int g_gw_port = -1;

/* Read one line (no newline) from fd. False on EOF/error/overflow. */
static bool gw_read_line(int fd, char *out, size_t cap)
{
    size_t n = 0;
    while (n + 1 < cap) {
        char c;
        ssize_t r = read(fd, &c, 1);
        if (r <= 0)
            return false;
        if (c == '\n')
            break;
        if (c != '\r')
            out[n++] = c;
    }
    out[n] = '\0';
    return true;
}

/* Spawn the gateway; parse its `ready port=N` line. True when serving. */
static bool gw_spawn(const char *bin, const char *node, const char *state)
{
    int fds[2];
    char line[256];
    if (pipe(fds) != 0)
        return false;
    g_gw_pid = fork();
    if (g_gw_pid < 0) {
        close(fds[0]);
        close(fds[1]);
        return false;
    }
    if (g_gw_pid == 0) {
        char *const argv[] = {(char *)bin, NULL};
        dup2(fds[1], STDOUT_FILENO);
        close(fds[0]);
        close(fds[1]);
        setenv("FLEET_GW_PORT", "0", 1);
        setenv("FLEET_GW_NODE", node, 1);
        setenv("FLEET_GW_OWNER_KEY", "gw-test-owner-key", 1);
        setenv("XDG_STATE_HOME", state, 1);
        execv(bin, argv);
        _exit(127);
    }
    close(fds[1]);
    if (!gw_read_line(fds[0], line, sizeof(line))) {
        close(fds[0]);
        return false;
    }
    close(fds[0]);
    if (sscanf(line, "ready port=%d", &g_gw_port) != 1 || g_gw_port <= 0)
        return false;
    return true;
}

static void gw_stop(void)
{
    int st = 0;
    if (g_gw_pid < 0)
        return;
    kill(g_gw_pid, SIGTERM);
    waitpid(g_gw_pid, &st, 0);
    g_gw_pid = -1;
    g_gw_port = -1;
}

/* One HTTP exchange over loopback. Returns the body (after the blank
 * line) malloc'd, with the status code out. NULL on transport failure. */
static char *gw_exchange(const char *request, int *status)
{
    int fd;
    struct sockaddr_in v4;
    char *buf, *body;
    size_t cap = GW_TEST_CAP, n = 0;
    ssize_t r;
    *status = 0;
    fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0)
        return NULL;
    memset(&v4, 0, sizeof(v4));
    v4.sin_family = AF_INET;
    v4.sin_port = htons((uint16_t)g_gw_port);
    v4.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    if (connect(fd, (struct sockaddr *)&v4, sizeof(v4)) != 0) {
        close(fd);
        return NULL;
    }
    {
        size_t left = strlen(request), off = 0;
        while (left > 0) {
            r = write(fd, request + off, left);
            if (r <= 0) {
                close(fd);
                return NULL;
            }
            off += (size_t)r;
            left -= (size_t)r;
        }
    }
    buf = malloc(cap);
    if (!buf) {
        close(fd);
        return NULL;
    }
    for (;;) {
        if (n + 4096 >= cap) {
            close(fd);
            free(buf);
            return NULL;
        }
        r = read(fd, buf + n, cap - n - 1);
        if (r == 0)
            break;
        if (r < 0) {
            close(fd);
            free(buf);
            return NULL;
        }
        n += (size_t)r;
    }
    close(fd);
    buf[n] = '\0';
    if (sscanf(buf, "HTTP/1.1 %d", status) != 1) {
        free(buf);
        return NULL;
    }
    body = strstr(buf, "\r\n\r\n");
    if (!body) {
        free(buf);
        return NULL;
    }
    body += 4;
    {
        size_t blen = n - (size_t)(body - buf);
        char *out = malloc(blen + 1);
        if (!out) {
            free(buf);
            return NULL;
        }
        memcpy(out, body, blen);
        out[blen] = '\0';
        free(buf);
        return out;
    }
}

static char *gw_post(const char *path, const char *json, int *status)
{
    char req[GW_TEST_CAP];
    int n = snprintf(req, sizeof(req),
                     "POST %s HTTP/1.1\r\nHost: x\r\nContent-Type: "
                     "application/json\r\nContent-Length: %zu\r\n"
                     "Connection: close\r\n\r\n%s",
                     path, strlen(json), json);
    if (n <= 0 || (size_t)n >= sizeof(req))
        return NULL;
    return gw_exchange(req, status);
}

static char *gw_post_auth(const char *path, const char *json,
                         const char *bearer, int *status)
{
    char req[GW_TEST_CAP];
    int n;
    if (bearer)
        n = snprintf(req, sizeof(req),
                     "POST %s HTTP/1.1\r\nHost: x\r\nContent-Type: "
                     "application/json\r\nAuthorization: Bearer %s\r\n"
                     "Content-Length: %zu\r\n"
                     "Connection: close\r\n\r\n%s",
                     path, bearer, strlen(json), json);
    else
        n = snprintf(req, sizeof(req),
                     "POST %s HTTP/1.1\r\nHost: x\r\nContent-Type: "
                     "application/json\r\n"
                     "Content-Length: %zu\r\n"
                     "Connection: close\r\n\r\n%s",
                     path, strlen(json), json);
    if (n <= 0 || (size_t)n >= sizeof(req))
        return NULL;
    return gw_exchange(req, status);
}

static char *gw_get(const char *path, int *status)
{
    char req[512];
    int n = snprintf(req, sizeof(req),
                     "GET %s HTTP/1.1\r\nHost: x\r\nConnection: close\r\n\r\n",
                     path);
    if (n <= 0 || (size_t)n >= sizeof(req))
        return NULL;
    return gw_exchange(req, status);
}

static bool gw_body_has(const char *body, const char *needle)
{
    return body && needle && strstr(body, needle) != NULL;
}

/* Loopback socket to the test gateway, or -1. */
static int gw_sock_open(void)
{
    int fd;
    struct sockaddr_in v4;
    fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0)
        return -1;
    memset(&v4, 0, sizeof(v4));
    v4.sin_family = AF_INET;
    v4.sin_port = htons((uint16_t)g_gw_port);
    v4.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
    if (connect(fd, (struct sockaddr *)&v4, sizeof(v4)) != 0) {
        close(fd);
        return -1;
    }
    return fd;
}

/* Whole request out, whole response back (NUL-terminated), or NULL. */
static char *gw_sock_roundtrip(int fd, const char *req)
{
    char *buf;
    size_t cap = 65536, len = 0;
    ssize_t r;
    size_t left = strlen(req), off = 0;
    while (left > 0) {
        r = write(fd, req + off, left);
        if (r <= 0) {
            close(fd);
            return NULL;
        }
        off += (size_t)r;
        left -= (size_t)r;
    }
    buf = malloc(cap);
    if (!buf) {
        close(fd);
        return NULL;
    }
    for (;;) {
        if (len + 4096 >= cap)
            break;
        r = read(fd, buf + len, cap - len - 1);
        if (r <= 0)
            break;
        len += (size_t)r;
    }
    close(fd);
    if (len == 0) {
        free(buf);
        return NULL;
    }
    buf[len] = '\0';
    return buf;
}

/* Location header out of a 302 response, or NULL. */
static char *gw_location_of(char *resp)
{
    char *p, *eol, *out;
    int st = 0;
    if (sscanf(resp, "HTTP/1.1 %d", &st) != 1 || st != 302)
        return NULL;
    p = strstr(resp, "\r\nLocation:");
    if (!p)
        p = strstr(resp, "\r\nlocation:");
    if (!p)
        return NULL;
    p = strchr(p + 2, ':') + 1;
    while (*p == ' ' || *p == '\t')
        p++;
    eol = strstr(p, "\r\n");
    if (!eol)
        return NULL;
    out = malloc((size_t)(eol - p) + 1);
    if (!out)
        return NULL;
    memcpy(out, p, (size_t)(eol - p));
    out[eol - p] = '\0';
    return out;
}

/* POST form-encoded; returns the Location header value, or NULL. */
static char *gw_post_location(const char *path, const char *form)
{
    char req[GW_TEST_CAP];
    int n = snprintf(req, sizeof(req),
                     "POST %s HTTP/1.1\r\nHost: x\r\nContent-Type: "
                     "application/x-www-form-urlencoded\r\n"
                     "Content-Length: %zu\r\n"
                     "Connection: close\r\n\r\n%s",
                     path, strlen(form), form);
    int fd;
    char *resp, *loc;
    if (n <= 0 || (size_t)n >= sizeof(req))
        return NULL;
    fd = gw_sock_open();
    if (fd < 0)
        return NULL;
    resp = gw_sock_roundtrip(fd, req);
    if (!resp)
        return NULL;
    loc = gw_location_of(resp);
    free(resp);
    return loc;
}

/* 32-hex value by JSON key out of a body. False when absent/misshapen. */
static bool gw_body_hex(const char *body, const char *key, char *out)
{
    char pat[80];
    const char *p;
    size_t i;
    if (snprintf(pat, sizeof(pat), "\"%s\":\"", key) < 0)
        return false;
    p = body ? strstr(body, pat) : NULL;
    if (!p)
        return false;
    p += strlen(pat);
    for (i = 0; i < 32; i++) {
        char c = p[i];
        bool hex = (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f');
        if (!hex)
            return false;
        out[i] = c;
    }
    out[32] = '\0';
    return true;
}

/* Run the node CLI: <node> fleet steer <verb> --input=<json>. Captured
 * stdout malloc'd; NULL on any failure. No shell. */
static char *gw_node_run(const char *node, const char *verb, const char *in)
{
    int fds[2];
    pid_t pid;
    char arg[8192];
    char *out = NULL;
    size_t cap = 65536, n = 0;
    int sn = snprintf(arg, sizeof(arg), "--input=%s", in);
    if (sn <= 0 || (size_t)sn >= sizeof(arg))
        return NULL;
    if (pipe(fds) != 0)
        return NULL;
    pid = fork();
    if (pid < 0) {
        close(fds[0]);
        close(fds[1]);
        return NULL;
    }
    if (pid == 0) {
        char *const argv[] = {(char *)node, (char *)"fleet",
                              (char *)"steer", (char *)verb, arg, NULL};
        dup2(fds[1], STDOUT_FILENO);
        close(fds[0]);
        close(fds[1]);
        execv(node, argv);
        _exit(127);
    }
    close(fds[1]);
    out = malloc(cap);
    if (!out) {
        close(fds[0]);
        waitpid(pid, NULL, 0);
        return NULL;
    }
    for (;;) {
        ssize_t r;
        if (n + 4096 >= cap)
            break;
        r = read(fds[0], out + n, cap - n - 1);
        if (r <= 0)
            break;
        n += (size_t)r;
    }
    close(fds[0]);
    waitpid(pid, NULL, 0);
    if (n == 0) {
        free(out);
        return NULL;
    }
    out[n] = '\0';
    return out;
}

/* Mint a steering grant through the node CLI; copies the 32-hex id out. */
static bool gw_mint(const char *node, const char *scopes, char *id_out)
{
    char in[256];
    char *reply;
    const char *p;
    int sn = snprintf(in, sizeof(in),
                      "{\"action\":\"mint\",\"scopes\":\"%s\"}", scopes);
    if (sn <= 0 || (size_t)sn >= sizeof(in))
        return false;
    reply = gw_node_run(node, "grant", in);
    if (!reply)
        return false;
    p = strstr(reply, "\"id\":\"");
    if (!p || strlen(p + 6) < 32) {
        free(reply);
        return false;
    }
    memcpy(id_out, p + 6, 32);
    id_out[32] = '\0';
    free(reply);
    return true;
}

static const char *gw_bin(const char *env, const char *dflt)
{
    const char *v = getenv(env);
    return v && v[0] ? v : dflt;
}

/* First mail seq out of an escaped send body (\"seq\":N). -1 when absent. */
static long long gw_body_seq(const char *body)
{
    const char *p = body ? strstr(body, "\\\"seq\\\":") : NULL;
    char *end = NULL;
    long long s;
    if (!p)
        return -1;
    s = strtoll(p + 8, &end, 10);
    if (end == p + 8 || s < 0)
        return -1;
    return s;
}

/* Receiver-side ack through the real mail leaf, in-process (receivers act
 * locally; the gateway only ever reads). The mail CLI leaf is compat-only,
 * so fork/exec cannot ack: same pattern as the steer group's fmx_ack. */
static bool gw_mail_ack(const char *agent, long long cursor)
{
    struct json_value input;
    struct zcl_command_request request;
    struct zcl_command_reply reply;
    bool ok;
    json_init(&input);
    json_set_object(&input);
    memset(&request, 0, sizeof(request));
    request.input = &input;
    request.spec =
        zcl_command_registry_find(zcl_command_catalog(), "dev.agent.mail",
                                  NULL);
    zcl_command_reply_init(&reply, "zcl.agent_mail.v1");
    (void)json_push_kv_str(&input, "action", "ack");
    (void)json_push_kv_str(&input, "agent", agent);
    (void)json_push_kv_int(&input, "cursor", cursor);
    zcl_native_handle_dev_agent_mail(&request, &reply);
    ok = reply.status == ZCL_COMMAND_STATUS_PASSED;
    zcl_command_reply_free(&reply);
    json_free(&input);
    return ok;
}

static int gw_t_routes(void)
{
    int failures = 0;
    TEST("gateway: healthz, 404 and POST-only steer") {
        int st = 0;
        char *b = gw_get("/healthz", &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 200);
        ASSERT(gw_body_has(b, "\"ok\":true"));
        free(b);
        b = gw_get("/nope", &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 404);
        free(b);
        b = gw_get("/steer", &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 405);
        free(b);
        PASS();
    }
_test_next:;
    return failures;
}

static int gw_t_handshake(void)
{
    int failures = 0;
    TEST("gateway: initialize negotiates, tools list the verbs") {
        int st = 0;
        char *b = gw_post("/steer",
                          "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":"
                          "\"initialize\",\"params\":{\"protocolVersion\":"
                          "\"2025-06-18\"}}",
                          &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 200);
        ASSERT(gw_body_has(b, "\"protocolVersion\":\"2025-06-18\""));
        ASSERT(gw_body_has(b, "z23-fleet-gateway"));
        free(b);
        b = gw_post("/steer",
                    "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/list\"}",
                    &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"name\":\"steer_brief\""));
        ASSERT(gw_body_has(b, "\"name\":\"steer_send\""));
        ASSERT(gw_body_has(b, "\"name\":\"steer_evidence\""));
        free(b);
        b = gw_post("/steer",
                    "{\"jsonrpc\":\"2.0\",\"id\":3,\"method\":\"nope\"}",
                    &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"code\":-32601"));
        free(b);
        b = gw_post("/steer", "{oops", &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"code\":-32700"));
        free(b);
        PASS();
    }
_test_next:;
    return failures;
}

static int gw_t_calls(void)
{
    int failures = 0;
    TEST("gateway: brief, send, duplicate and refusal round-trip") {
        const char *node = gw_bin("Z23_TEST_NODE_BIN", GW_TEST_NODE_DEFAULT);
        char gid[64];
        char args[512];
        char *b;
        int st = 0, sn;
        ASSERT(gw_mint(node, "brief,send,evidence", gid));
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":10,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_brief\","
                      "\"arguments\":{\"grant\":\"%s\"}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "agents"));
        free(b);
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":11,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_send\","
                      "\"arguments\":{\"grant\":\"%s\",\"items\":[{\"to\":"
                      "\"gw-agent\",\"body\":\"probe\",\"ref\":\"gw-1\","
                      "\"idempotency_key\":\"gw-k1\"}]}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "queued"));
        ASSERT(!gw_body_has(b, "duplicate\\\":true"));
        free(b);
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "duplicate\\\":true"));
        free(b);
        /* Same key, changed payload: refused, never a duplicate. */
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":12,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_send\","
                      "\"arguments\":{\"grant\":\"%s\",\"items\":[{\"to\":"
                      "\"gw-agent\",\"body\":\"changed\",\"ref\":\"gw-1\","
                      "\"idempotency_key\":\"gw-k1\"}]}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "refused"));
        ASSERT(gw_body_has(b, "IDEMPOTENCY_CONFLICT"));
        ASSERT(!gw_body_has(b, "duplicate\\\":true"));
        free(b);
        /* Evidence before the receiver ack: delivered, not acknowledged. */
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":13,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_evidence\","
                      "\"arguments\":{\"grant\":\"%s\",\"type\":\"mail\","
                      "\"ref\":\"gw-1\"}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "delivered"));
        ASSERT(!gw_body_has(b, "acknowledged"));
        free(b);
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":14,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_send\","
                      "\"arguments\":{\"grant\":\"%s\",\"items\":[{\"to\":"
                      "\"gw-agent\",\"body\":\"probe\",\"ref\":\"gw-1\","
                      "\"idempotency_key\":\"gw-k1\"}]}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        {
            long long seq = gw_body_seq(b);
            ASSERT(seq > 0);
            ASSERT(gw_mail_ack("gw-agent", seq));
        }
        free(b);
        /* Evidence after the receiver ack: the gateway reports it. */
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":15,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_evidence\","
                      "\"arguments\":{\"grant\":\"%s\",\"type\":\"mail\","
                      "\"ref\":\"gw-1\"}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "acknowledged"));
        free(b);
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":16,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_send\","
                      "\"arguments\":{\"grant\":\"00000000000000000000000000"
                      "00000000\",\"items\":[{\"to\":\"gw-agent\",\"body\":"
                      "\"x\",\"ref\":\"gw-1\",\"idempotency_key\":"
                      "\"gw-k9\"}]}}}");
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post("/steer", args, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":true"));
        ASSERT(gw_body_has(b, "STEER_GRANT_UNKNOWN"));
        free(b);
        PASS();
    }
_test_next:;
    return failures;
}

static int gw_t_auth(void);
/* RFC 7636 Appendix B vector: the gateway's S256 must reproduce it. */
static const char *const GW_OAUTH_VERIFIER =
    "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk";
static const char *const GW_OAUTH_CHALLENGE =
    "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM";

static int gw_t_oauth(void)
{
    int failures = 0;
    TEST("gateway: OAuth discovery, sign-in, tokens, bearer grants") {
        const char *node = gw_bin("Z23_TEST_NODE_BIN", GW_TEST_NODE_DEFAULT);
        char cid[33], token[33], code[33], gid2[64];
        char args[1024], form[2048];
        char *b, *loc;
        const char *cp;
        size_t i;
        int st = 0, sn;
        /* Discovery documents the resource and the server. */
        b = gw_get("/.well-known/oauth-protected-resource", &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 200);
        ASSERT(gw_body_has(b, "\"scopes_supported\""));
        ASSERT(gw_body_has(b, "bearer_methods_supported"));
        free(b);
        b = gw_get("/.well-known/oauth-authorization-server", &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"token_endpoint\""));
        ASSERT(gw_body_has(b, "code_challenge_methods_supported"));
        free(b);
        /* Dynamic registration, then a bad redirect refused. */
        b = gw_post("/oauth/register",
                    "{\"redirect_uris\":[\"https://client.test/cb\"]}", &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 201);
        ASSERT(gw_body_hex(b, "client_id", cid));
        free(b);
        b = gw_post("/oauth/register",
                    "{\"redirect_uris\":[\"http://evil.test/cb\"]}", &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "invalid_redirect_uri"));
        free(b);
        /* Approval form for a valid request, refusal for a stranger. */
        sn = snprintf(args, sizeof(args),
                      "/oauth/authorize?response_type=code&client_id=%s"
                      "&redirect_uri=https://client.test/cb"
                      "&scope=brief%%20send&state=xyz&code_challenge=%s"
                      "&code_challenge_method=S256",
                      cid, GW_OAUTH_CHALLENGE);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_get(args, &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 200);
        ASSERT(gw_body_has(b, "Z23 Fleet sign-in"));
        free(b);
        b = gw_get("/oauth/authorize?response_type=code&client_id=0000000000"
                   "0000000000000000000000"
                   "&redirect_uri=https://client.test/cb&scope=brief"
                   "&code_challenge=x&code_challenge_method=S256",
                   &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "invalid_request"));
        free(b);
        /* Approval needs the owner key; the wrong key is denied. */
        sn = snprintf(form, sizeof(form),
                      "response_type=code&client_id=%s"
                      "&redirect_uri=https://client.test/cb"
                      "&scope=brief%%20send&state=xyz&code_challenge=%s"
                      "&code_challenge_method=S256"
                      "&owner_key=wrong&approve=1",
                      cid, GW_OAUTH_CHALLENGE);
        ASSERT(sn > 0 && (size_t)sn < sizeof(form));
        b = gw_post("/oauth/authorize", form, &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 403);
        ASSERT(gw_body_has(b, "access_denied"));
        free(b);
        /* Correct approval redirects with a single-use code. */
        sn = snprintf(form, sizeof(form),
                      "response_type=code&client_id=%s"
                      "&redirect_uri=https://client.test/cb"
                      "&scope=brief%%20send&state=xyz&code_challenge=%s"
                      "&code_challenge_method=S256"
                      "&owner_key=gw-test-owner-key&approve=1",
                      cid, GW_OAUTH_CHALLENGE);
        ASSERT(sn > 0 && (size_t)sn < sizeof(form));
        loc = gw_post_location("/oauth/authorize", form);
        ASSERT(loc != NULL);
        cp = strstr(loc, "code=");
        ASSERT(cp != NULL);
        for (i = 0; i < 32; i++)
            code[i] = cp[5 + i];
        code[32] = '\0';
        ASSERT(gw_body_has(loc, "state=xyz"));
        free(loc);
        /* Wrong verifier refused; the RFC vector exchanges. */
        sn = snprintf(form, sizeof(form),
                      "grant_type=authorization_code&code=%s"
                      "&redirect_uri=https://client.test/cb&client_id=%s"
                      "&code_verifier=wrong",
                      code, cid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(form));
        b = gw_post("/oauth/token", form, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "invalid_grant"));
        free(b);
        sn = snprintf(form, sizeof(form),
                      "grant_type=authorization_code&code=%s"
                      "&redirect_uri=https://client.test/cb&client_id=%s"
                      "&code_verifier=%s",
                      code, cid, GW_OAUTH_VERIFIER);
        ASSERT(sn > 0 && (size_t)sn < sizeof(form));
        b = gw_post("/oauth/token", form, &st);
        ASSERT(b != NULL);
        ASSERT_EQ(st, 200);
        ASSERT(gw_body_hex(b, "access_token", token));
        ASSERT(gw_body_has(b, "\"scope\":\"brief send\""));
        free(b);
        /* The code is single-use. */
        b = gw_post("/oauth/token", form, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "invalid_grant"));
        free(b);
        /* The token is a scoped grant: bearer brief passes. */
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":20,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":\"steer_brief\","
                         "\"arguments\":{}}}",
                         token, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        free(b);
        /* Unknown bearer is refused with the typed grant code. */
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":21,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":\"steer_brief\","
                         "\"arguments\":{}}}",
                         "00000000000000000000000000000000", &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":true"));
        ASSERT(gw_body_has(b, "STEER_GRANT_UNKNOWN"));
        free(b);
        /* Header and argument must agree when both travel. */
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":22,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":\"steer_brief\","
                         "\"arguments\":{\"grant\":"
                         "\"00000000000000000000000000000000\"}}}",
                         token, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"code\":-32002"));
        ASSERT(gw_body_has(b, "conflicting grants"));
        free(b);
        /* Wrong scope through the bearer: the node refuses. */
        ASSERT(gw_mint(node, "brief", gid2));
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":23,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":\"steer_send\","
                         "\"arguments\":{\"items\":[{\"to\":\"gw-agent\","
                         "\"body\":\"x\",\"ref\":\"r-oa\","
                         "\"idempotency_key\":\"k-oa\"}]}}}",
                         gid2, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "STEER_GRANT_SCOPE"));
        free(b);
        /* Revoked through the bearer: the node refuses. */
        {
            char in[256], *reply;
            sn = snprintf(in, sizeof(in),
                          "{\"action\":\"revoke\",\"id\":\"%s\"}", token);
            ASSERT(sn > 0 && (size_t)sn < sizeof(in));
            reply = gw_node_run(node, "grant", in);
            ASSERT(reply != NULL);
            free(reply);
        }
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":24,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":\"steer_brief\","
                         "\"arguments\":{}}}",
                         token, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "STEER_GRANT_REVOKED"));
        free(b);
        /* No credential at all is refused before the node is forked:
         * a remote caller can never ride local-operator authority. */
        b = gw_post("/steer",
                    "{\"jsonrpc\":\"2.0\",\"id\":25,\"method\":\"tools/call\","
                    "\"params\":{\"name\":\"steer_brief\",\"arguments\":{}}}",
                    &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"code\":-32001"));
        ASSERT(gw_body_has(b, "grant required"));
        free(b);
        PASS();
    }
_test_next:;
    return failures;
}

/* Worker-lifecycle regression: the authorized-task journey through the real
 * gateway, mail, ack, queue and evidence leaves in one isolated lane.
 * send -> queued -> brief delivered -> receiver ack -> acknowledged ->
 * real queue outcome naming the same ref -> brief completed -> evidence
 * returns the exact outcome row. Restart, idempotency and revoke legs
 * follow in their own cases. No case touches the network beyond loopback,
 * the wallet, deployment, or soak paths. */
#define GW_LIFE_REF "gw-life-001"
#define GW_LIFE_KEY "gw-life-key-001"
#define GW_LIFE_TO "gw-worker"
#define GW_LIFE_FROM "gw-chat"

static char g_gw_state[512];
static char g_life_gid[64];
static long long g_life_seq = -1;

/* tools/call envelope around a caller-built arguments object. */
static char *gw_tool(const char *verb, const char *argsjson, int id, int *st)
{
    char req[4096];
    int sn = snprintf(req, sizeof(req),
                      "{\"jsonrpc\":\"2.0\",\"id\":%d,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"%s\",\"arguments\":%s}}",
                      id, verb, argsjson);
    if (sn <= 0 || (size_t)sn >= sizeof(req))
        return NULL;
    return gw_post("/steer", req, st);
}

/* One in-process dev.agent.queue call. True when the leaf passes. */
struct gw_qcall {
    struct json_value input;
    struct zcl_command_request req;
    struct zcl_command_reply rep;
};

static void gw_qbegin(struct gw_qcall *c, const char *action)
{
    json_init(&c->input);
    json_set_object(&c->input);
    memset(&c->req, 0, sizeof(c->req));
    c->req.input = &c->input;
    c->req.spec =
        zcl_command_registry_find(zcl_command_catalog(), "dev.agent.queue",
                                  NULL);
    zcl_command_reply_init(&c->rep, "zcl.agent_queue.v1");
    (void)json_push_kv_str(&c->input, "action", action);
}

static bool gw_qrun(struct gw_qcall *c)
{
    zcl_native_handle_dev_agent_queue(&c->req, &c->rep);
    return c->rep.status == ZCL_COMMAND_STATUS_PASSED;
}

static void gw_qend(struct gw_qcall *c)
{
    zcl_command_reply_free(&c->rep);
    json_free(&c->input);
}

static bool gw_qpost(const char *name)
{
    struct gw_qcall c;
    bool ok;
    gw_qbegin(&c, "post");
    (void)json_push_kv_str(&c.input, "kind", "leaf");
    (void)json_push_kv_str(&c.input, "name", name);
    ok = gw_qrun(&c);
    gw_qend(&c);
    return ok;
}

static bool gw_qnext(char *state, size_t cap)
{
    struct gw_qcall c;
    bool ok = false;
    const struct json_value *v;
    const char *s;
    gw_qbegin(&c, "next");
    if (gw_qrun(&c)) {
        v = json_get(&c.rep.data, "state");
        s = (v && v->type == JSON_STR) ? json_get_str(v) : NULL;
        if (s && snprintf(state, cap, "%s", s) > 0)
            ok = true;
    }
    gw_qend(&c);
    return ok;
}

/* Reap and require one outcome row naming the ref with a PASS verdict. */
static bool gw_qreap_pass(const char *name)
{
    struct gw_qcall c;
    const struct json_value *rows, *r, *v;
    const char *n, *verdict;
    size_t i, nrows;
    bool found = false;
    gw_qbegin(&c, "reap");
    if (!gw_qrun(&c)) {
        gw_qend(&c);
        return false;
    }
    rows = json_get(&c.rep.data, "outcomes");
    if (rows && rows->type == JSON_ARR) {
        nrows = json_size(rows);
        for (i = 0; i < nrows; i++) {
            r = json_at(rows, i);
            if (!r || r->type != JSON_OBJ)
                continue;
            v = json_get(r, "name");
            n = (v && v->type == JSON_STR) ? json_get_str(v) : NULL;
            v = json_get(r, "verdict");
            verdict = (v && v->type == JSON_STR) ? json_get_str(v) : NULL;
            if (n && verdict && strcmp(n, name) == 0 &&
                strcmp(verdict, "PASS") == 0)
                found = true;
        }
    }
    gw_qend(&c);
    return found;
}

static bool gw_write_text(const char *path, const char *text)
{
    FILE *f = fopen(path, "wb");
    size_t len;
    bool wrote;
    if (!f)
        return false;
    len = strlen(text);
    wrote = fwrite(text, 1, len, f) == len;
    return fclose(f) == 0 && wrote;
}

static bool gw_mkdirp(const char *path)
{
    char acc[1100];
    size_t i, n = strlen(path);
    if (n == 0 || n >= sizeof(acc))
        return false;
    for (i = 1; i <= n; i++) {
        if (path[i] != '/' && path[i] != '\0')
            continue;
        memcpy(acc, path, i);
        acc[i] = '\0';
        if (mkdir(acc, 0700) != 0 && errno != EEXIST)
            return false;
    }
    return true;
}

/* Minimal fake engine-unit on PATH: writes a PASS receipt for --state-dir
 * and exits. Same fixture pattern as the queue group's fake. */
static const char k_gw_fake[] =
    "#!/bin/sh\n"
    "st=\"\"\n"
    "prev=\"\"\n"
    "for a in \"$@\"; do\n"
    "  case \"$a\" in\n"
    "    --state-dir=*) st=\"${a#--state-dir=}\";;\n"
    "    --state-dir) prev=\"want\";;\n"
    "    *) if [ \"$prev\" = \"want\" ]; then st=\"$a\"; prev=\"\"; fi;;\n"
    "  esac\n"
    "done\n"
    "[ -n \"$st\" ] || exit 2\n"
    "printf '{\"verdict\":\"PASS\"}\n' > \"$st/receipt.json\"\n"
    "echo \"dispatching $st\"\n"
    "echo \"rc=0\"\n"
    "exit 0\n";

static char g_gw_saved_path[9000];

static bool gw_fake_unit(void)
{
    char base[512], bindir[1024], prog[1100], path[9000];
    const char *old = getenv("PATH");
    test_make_tmpdir(base, sizeof(base), "fleet_gateway", "life_bin");
    if (snprintf(bindir, sizeof(bindir), "%s/bin", base) < 0)
        return false;
    if (mkdir(bindir, 0700) != 0)
        return false;
    if (snprintf(prog, sizeof(prog), "%s/zclassic23-engine-unit",
                 bindir) < 0)
        return false;
    if (!gw_write_text(prog, k_gw_fake))
        return false;
    if (chmod(prog, 0755) != 0)
        return false;
    if (!old || snprintf(g_gw_saved_path, sizeof(g_gw_saved_path), "%s",
                         old) < 0)
        return false;
    if (snprintf(path, sizeof(path), "%s:%s", bindir, old) < 0)
        return false;
    return setenv("PATH", path, 1) == 0;
}

static void gw_path_restore(void)
{
    if (g_gw_saved_path[0])
        setenv("PATH", g_gw_saved_path, 1);
}

/* Warm pool worktree plus pool.txt under the isolated queue dir. */
static bool gw_pool(char *qd, size_t qdcap)
{
    const char *xdg = getenv("XDG_STATE_HOME");
    char base[512], wt[1024], warm[1100], pool[1200], line[1100];
    FILE *f;
    if (!xdg || snprintf(qd, qdcap, "%s/z23/dev/queue", xdg) < 0)
        return false;
    if (!gw_mkdirp(qd))
        return false;
    test_make_tmpdir(base, sizeof(base), "fleet_gateway", "life_wt");
    if (snprintf(wt, sizeof(wt), "%s/wt", base) < 0)
        return false;
    if (mkdir(wt, 0700) != 0)
        return false;
    if (snprintf(warm, sizeof(warm), "%s/.eu-warm", wt) < 0)
        return false;
    if (!gw_write_text(warm, "warm\n"))
        return false;
    if (snprintf(pool, sizeof(pool), "%s/pool.txt", qd) < 0)
        return false;
    if (snprintf(line, sizeof(line), "%s\n", wt) < 0)
        return false;
    f = fopen(pool, "wb");
    if (!f)
        return false;
    if (fwrite(line, 1, strlen(line), f) != strlen(line)) {
        (void)fclose(f);
        return false;
    }
    return fclose(f) == 0;
}

static bool gw_poll_file(const char *path)
{
    int i;
    struct timespec req;
    for (i = 0; i < 150; i++) {
        if (access(path, R_OK) == 0)
            return true;
        req.tv_sec = 0;
        req.tv_nsec = 100000000L;
        (void)nanosleep(&req, NULL); /* real-clock: bounded wait for a detached engine-unit child outside this address space; completion arrives in kernel time and no fake-clock seam reaches it */
    }
    return access(path, R_OK) == 0;
}

static int gw_t_life_send_ack(void)
{
    int failures = 0;
    TEST("lifecycle: send queues, brief reports delivered then acknowledged") {
        const char *node = gw_bin("Z23_TEST_NODE_BIN", GW_TEST_NODE_DEFAULT);
        char args[1024];
        char *b;
        int st = 0, sn;
        long long seq;
        ASSERT(gw_mint(node, "brief,send,evidence", g_life_gid));
        sn = snprintf(args, sizeof(args),
                      "{\"grant\":\"%s\",\"from\":\"" GW_LIFE_FROM "\","
                      "\"items\":[{\"to\":\"" GW_LIFE_TO "\","
                      "\"body\":\"Lifecycle probe PINEAPPLE\","
                      "\"ref\":\"" GW_LIFE_REF "\","
                      "\"idempotency_key\":\"" GW_LIFE_KEY "\"}]}",
                      g_life_gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_tool("steer_send", args, 30, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "queued"));
        seq = gw_body_seq(b);
        free(b);
        ASSERT(seq > 0);
        g_life_seq = seq;
        /* Delivered on pull, never ahead: no ack, no outcome yet. */
        sn = snprintf(args, sizeof(args),
                      "{\"grant\":\"%s\",\"since\":%lld}", g_life_gid,
                      seq - 1);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_tool("steer_brief", args, 31, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "\"state\\\":\\\"delivered\\\""));
        ASSERT(!gw_body_has(b, "acknowledged"));
        ASSERT(!gw_body_has(b, "completed"));
        free(b);
        /* Receiver ack through the real mail leaf. */
        ASSERT(gw_mail_ack(GW_LIFE_TO, seq));
        b = gw_tool("steer_brief", args, 32, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "\"state\\\":\\\"acknowledged\\\""));
        ASSERT(!gw_body_has(b, "completed"));
        free(b);
        PASS();
    }
_test_next:;
    return failures;
}

static int gw_t_life_complete(void)
{
    int failures = 0;
    TEST("lifecycle: real queue outcome completes the ref, evidence exact") {
        char args[1024];
        char qd[1100], receipt[1300], qstate[32];
        char *b;
        int st = 0, sn;
        bool reaped;
        ASSERT(g_life_seq > 0 && g_life_gid[0]);
        ASSERT(gw_fake_unit());
        ASSERT(gw_pool(qd, sizeof(qd)));
        ASSERT(gw_qpost(GW_LIFE_REF));
        ASSERT(gw_qnext(qstate, sizeof(qstate)));
        ASSERT_STR_EQ(qstate, "running");
        sn = snprintf(receipt, sizeof(receipt),
                      "%s/../engine/%s/a1/receipt.json", qd, GW_LIFE_REF);
        ASSERT(sn > 0 && (size_t)sn < sizeof(receipt));
        ASSERT(gw_poll_file(receipt));
        reaped = gw_qreap_pass(GW_LIFE_REF);
        gw_path_restore();
        ASSERT(reaped);
        /* The outcome names the ref: brief upgrades to completed. */
        sn = snprintf(args, sizeof(args),
                      "{\"grant\":\"%s\",\"since\":%lld}", g_life_gid,
                      g_life_seq - 1);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_tool("steer_brief", args, 33, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "\"state\\\":\\\"completed\\\""));
        free(b);
        /* Evidence returns the exact outcome row by ref. */
        sn = snprintf(args, sizeof(args),
                      "{\"grant\":\"%s\",\"type\":\"queue\",\"ref\":\""
                      GW_LIFE_REF "\"}",
                      g_life_gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_tool("steer_evidence", args, 34, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "\"name\\\":\\\"" GW_LIFE_REF "\\\""));
        ASSERT(gw_body_has(b, "\"verdict\\\":\\\"PASS\\\""));
        free(b);
        /* The directive row itself is still readable by ref. */
        sn = snprintf(args, sizeof(args),
                      "{\"grant\":\"%s\",\"type\":\"mail\",\"ref\":\""
                      GW_LIFE_REF "\"}",
                      g_life_gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_tool("steer_evidence", args, 35, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "\"ref\\\":\\\"" GW_LIFE_REF "\\\""));
        free(b);
        PASS();
    }
_test_next:;
    return failures;
}

static int gw_t_life_restart(void)
{
    int failures = 0;
    TEST("lifecycle: restart keeps completed, idempotent, revoke-safe") {
        const char *node = gw_bin("Z23_TEST_NODE_BIN", GW_TEST_NODE_DEFAULT);
        const char *bin = gw_bin("Z23_TEST_GATEWAY_BIN", GW_TEST_BIN_DEFAULT);
        char args[1024];
        char gid2[64];
        char *b;
        int st = 0, sn;
        ASSERT(g_life_seq > 0 && g_life_gid[0]);
        /* Kill and restart the gateway mid-journey: state is file-backed. */
        gw_stop();
        ASSERT(gw_spawn(bin, node, g_gw_state));
        sn = snprintf(args, sizeof(args),
                      "{\"grant\":\"%s\",\"since\":%lld}", g_life_gid,
                      g_life_seq - 1);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_tool("steer_brief", args, 36, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"state\\\":\\\"completed\\\""));
        free(b);
        /* Same key and payload: reconciled, zero duplicate work. */
        sn = snprintf(args, sizeof(args),
                      "{\"grant\":\"%s\",\"from\":\"" GW_LIFE_FROM "\","
                      "\"items\":[{\"to\":\"" GW_LIFE_TO "\","
                      "\"body\":\"Lifecycle probe PINEAPPLE\","
                      "\"ref\":\"" GW_LIFE_REF "\","
                      "\"idempotency_key\":\"" GW_LIFE_KEY "\"}]}",
                      g_life_gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_tool("steer_send", args, 37, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "duplicate\\\":true"));
        free(b);
        /* Same key, changed payload: refused, never a second row. */
        sn = snprintf(args, sizeof(args),
                      "{\"grant\":\"%s\",\"from\":\"" GW_LIFE_FROM "\","
                      "\"items\":[{\"to\":\"" GW_LIFE_TO "\","
                      "\"body\":\"Lifecycle probe ORANGE\","
                      "\"ref\":\"" GW_LIFE_REF "\","
                      "\"idempotency_key\":\"" GW_LIFE_KEY "\"}]}",
                      g_life_gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_tool("steer_send", args, 38, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "IDEMPOTENCY_CONFLICT"));
        ASSERT(!gw_body_has(b, "duplicate\\\":true"));
        free(b);
        /* Revoke blocks new calls but does not rewrite completed evidence. */
        {
            char in[256], *reply;
            sn = snprintf(in, sizeof(in),
                          "{\"action\":\"revoke\",\"id\":\"%s\"}",
                          g_life_gid);
            ASSERT(sn > 0 && (size_t)sn < sizeof(in));
            reply = gw_node_run(node, "grant", in);
            ASSERT(reply != NULL);
            free(reply);
        }
        sn = snprintf(args, sizeof(args), "{\"grant\":\"%s\"}", g_life_gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_tool("steer_brief", args, 39, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "STEER_GRANT_REVOKED"));
        free(b);
        ASSERT(gw_mint(node, "brief,send,evidence", gid2));
        sn = snprintf(args, sizeof(args),
                      "{\"grant\":\"%s\",\"type\":\"queue\",\"ref\":\""
                      GW_LIFE_REF "\"}",
                      gid2);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_tool("steer_evidence", args, 40, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "\"verdict\\\":\\\"PASS\\\""));
        free(b);
        PASS();
    }
_test_next:;
    return failures;
}

int test_fleet_gateway(void);
int test_fleet_gateway(void)
{
    int failures = 0;
    const char *bin = gw_bin("Z23_TEST_GATEWAY_BIN", GW_TEST_BIN_DEFAULT);
    const char *node = gw_bin("Z23_TEST_NODE_BIN", GW_TEST_NODE_DEFAULT);
    char state[512];
    const char *saved_xdg = getenv("XDG_STATE_HOME");
    char saved[4096];
    bool had_xdg = saved_xdg != NULL;
    test_make_tmpdir(state, sizeof(state), "fleet_gateway", "iso");
    if (strlen(state) + 8 >= sizeof(state))
        return 1;
    strcat(state, "/state");
    if (mkdir(state, 0700) != 0)
        return 1;
    /* The direct node runs (grant mint) must land in the same isolated
     * store the gateway child serves; save and restore the ambient root. */
    if (had_xdg) {
        if (snprintf(saved, sizeof(saved), "%s", saved_xdg) < 0)
            return 1;
    }
    if (setenv("XDG_STATE_HOME", state, 1) != 0)
        return 1;
    if (snprintf(g_gw_state, sizeof(g_gw_state), "%s", state) < 0)
        return 1;
    if (!gw_spawn(bin, node, state)) {
        if (had_xdg)
            setenv("XDG_STATE_HOME", saved, 1);
        else
            unsetenv("XDG_STATE_HOME");
        return 1;
    }
    failures += gw_t_routes();
    failures += gw_t_handshake();
    failures += gw_t_calls();
    failures += gw_t_auth();
    failures += gw_t_oauth();
    failures += gw_t_life_send_ack();
    failures += gw_t_life_complete();
    failures += gw_t_life_restart();
    /* No ASSERT lives here; the stop always runs on fall-through. */
    gw_stop();
    if (had_xdg)
        setenv("XDG_STATE_HOME", saved, 1);
    else
        unsetenv("XDG_STATE_HOME");
    if (failures == 0)
        printf("test_fleet_gateway: all passed\n");
    else
        printf("test_fleet_gateway: %d FAILED\n", failures);
    return failures;
}

static int gw_t_auth(void)
{
    int failures = 0;
    TEST("gateway: tool calls fail closed without exactly one grant") {
        const char *node = gw_bin("Z23_TEST_NODE_BIN", GW_TEST_NODE_DEFAULT);
        char gid[64];
        char args[512];
        char *b;
        int st = 0, sn;
        ASSERT(gw_mint(node, "brief,send,evidence", gid));
        /* No credential anywhere: refused before the node is forked. */
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":20,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":"
                         "\"steer_brief\",\"arguments\":{}}}",
                         NULL, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"code\":-32001"));
        ASSERT(gw_body_has(b, "grant required"));
        free(b);
        /* Header credential alone: carried to the node, brief succeeds. */
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":21,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":"
                         "\"steer_brief\",\"arguments\":{}}}",
                         gid, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        ASSERT(gw_body_has(b, "agents"));
        free(b);
        /* Header and argument agreeing: accepted. */
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":22,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_brief\","
                      "\"arguments\":{\"grant\":\"%s\"}}}",
                      gid);
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post_auth("/steer", args, gid, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":false"));
        free(b);
        /* Header and argument differing: refused as ambiguous. */
        sn = snprintf(args, sizeof(args),
                      "{\"jsonrpc\":\"2.0\",\"id\":23,\"method\":\"tools/"
                      "call\",\"params\":{\"name\":\"steer_brief\","
                      "\"arguments\":{\"grant\":\"00000000000000000000000000"
                      "00000000\"}}}");
        ASSERT(sn > 0 && (size_t)sn < sizeof(args));
        b = gw_post_auth("/steer", args, gid, &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"code\":-32002"));
        ASSERT(gw_body_has(b, "conflicting grants"));
        free(b);
        /* Non-token bytes in the header: refused, never forwarded. */
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":24,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":"
                         "\"steer_brief\",\"arguments\":{}}}",
                         "\",\"x\":1,//", &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"code\":-32002"));
        ASSERT(gw_body_has(b, "bad grant credential"));
        free(b);
        /* Unknown header credential: the node itself refuses it. */
        b = gw_post_auth("/steer",
                         "{\"jsonrpc\":\"2.0\",\"id\":25,\"method\":"
                         "\"tools/call\",\"params\":{\"name\":"
                         "\"steer_brief\",\"arguments\":{}}}",
                         "00000000000000000000000000000000", &st);
        ASSERT(b != NULL);
        ASSERT(gw_body_has(b, "\"isError\":true"));
        ASSERT(gw_body_has(b, "STEER_GRANT_UNKNOWN"));
        free(b);
        PASS();
    }
_test_next:;
    return failures;
}
#endif /* _WIN32 */
