/* Copyright 2026 Rhett Creighton - Apache License 2.0
 *
 * ACCEPTANCE BAR for fleet.mcp + fleet.mcp.grant
 * (tools/command/native_fleet_mcp.c).
 *
 * The thin remote-MCP adapter over the existing fleet leaves: brief composes
 * mail/queue/board/ledger in-process, send posts bounded directive batches
 * with idempotency keys, evidence returns one object per exact reference,
 * and the grant leaf mints/revokes scoped bearer grants.
 *
 * Written against an isolated platform state root, never the operator's
 * real state dir. The board and ledger siblings have no node and no
 * delegation here, so the tests pin their honest absence (missing[] /
 * EVIDENCE_UNAVAILABLE) rather than their data. No case touches the
 * network, sleeps, or polls. Do not edit this file to make the
 * implementation pass.
 */

#include "test/test_core.h"

#include "command/native_command.h"
#include "command/native_fleet.h"
#include "config/command_catalog.h"
#include "controllers/rpc_client.h"
#include "json/json.h"
#include "kernel/command_registry.h"
#include "platform/private_directory.h"

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#if defined(_WIN32)
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#else
#include <dirent.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#endif

#define FMX_BRIEF_PATH "fleet.mcp.brief"
#define FMX_SEND_PATH "fleet.mcp.send"
#define FMX_EVIDENCE_PATH "fleet.mcp.evidence"
#define FMX_GRANT_PATH "fleet.mcp.grant"

/* ── isolated state root (this group owns its own rig) ─────────────────── */

static char g_fmx_state[1024];
static bool g_fmx_had_root;
static bool g_fmx_isolated;
#if defined(_WIN32)
static wchar_t g_fmx_saved_root[32768];
#else
static char g_fmx_saved_root[4096];
#endif

static void fmx_fixture_fail(const char *context)
{
    fprintf(stderr, "fleet_mcp fixture: %s\n", context);
    abort();
}

#if defined(_WIN32)
static void fmx_isolate_env(const char *state)
{
    wchar_t root[1024];
    g_fmx_saved_root[0] = L'\0';
    SetLastError(ERROR_SUCCESS);
    DWORD length = GetEnvironmentVariableW(L"ZCL_STATE_ROOT", g_fmx_saved_root,
                                           32768);
    DWORD error = GetLastError();
    if (length >= 32768 || (length == 0 && error != ERROR_SUCCESS &&
                            error != ERROR_ENVVAR_NOT_FOUND))
        fmx_fixture_fail("could not preserve ZCL_STATE_ROOT");
    g_fmx_had_root = length > 0 || error == ERROR_SUCCESS;
    if (MultiByteToWideChar(CP_UTF8, MB_ERR_INVALID_CHARS, state, -1,
                            root, 1024) <= 0 ||
        !SetEnvironmentVariableW(L"ZCL_STATE_ROOT", root))
        fmx_fixture_fail("could not isolate ZCL_STATE_ROOT");
}
#else
static void fmx_isolate_env(const char *state)
{
    const char *original = getenv("XDG_STATE_HOME");
    g_fmx_had_root = original != NULL;
    if (original) {
        int n = snprintf(g_fmx_saved_root, sizeof(g_fmx_saved_root), "%s",
                         original);
        if (n < 0 || (size_t)n >= sizeof(g_fmx_saved_root))
            fmx_fixture_fail("could not preserve XDG_STATE_HOME");
    }
    if (setenv("XDG_STATE_HOME", state, 1) != 0)
        fmx_fixture_fail("could not isolate XDG_STATE_HOME");
}
#endif

static void fmx_isolate(const char *tag)
{
    char base[512];
    if (g_fmx_isolated)
        fmx_fixture_fail("previous state root has not been restored");
    test_make_tmpdir(base, sizeof(base), "fleet_mcp", tag);
    int n = snprintf(g_fmx_state, sizeof(g_fmx_state), "%s/state", base);
    if (n <= 0 || (size_t)n >= sizeof(g_fmx_state) ||
        !platform_private_directory_ensure(g_fmx_state))
        fmx_fixture_fail("could not create isolated state parent");
    fmx_isolate_env(g_fmx_state);
    g_fmx_isolated = true;
}

static void fmx_restore(void)
{
    if (!g_fmx_isolated) return;
#if defined(_WIN32)
    if (!SetEnvironmentVariableW(L"ZCL_STATE_ROOT",
                                 g_fmx_had_root ? g_fmx_saved_root : NULL))
        fmx_fixture_fail("could not restore ZCL_STATE_ROOT");
#else
    int rc = g_fmx_had_root ? setenv("XDG_STATE_HOME", g_fmx_saved_root, 1)
                            : unsetenv("XDG_STATE_HOME");
    if (rc != 0)
        fmx_fixture_fail("could not restore XDG_STATE_HOME");
#endif
    g_fmx_isolated = false;
}

/* ── one in-process invocation ─────────────────────────────────────────── */

struct fmx_call {
    struct json_value input;
    struct zcl_command_request request;
    struct zcl_command_reply reply;
};

static void fmx_begin(struct fmx_call *c, const char *path,
                      const char *schema)
{
    json_init(&c->input);
    json_set_object(&c->input);
    memset(&c->request, 0, sizeof(c->request));
    c->request.input = &c->input;
    c->request.spec =
        zcl_command_registry_find(zcl_command_catalog(), path, NULL);
    zcl_command_reply_init(&c->reply, schema);
}

static bool fmx_run(struct fmx_call *c,
                    void (*handler)(const struct zcl_command_request *,
                                    struct zcl_command_reply *))
{
    char why[256];
    if (c->request.spec &&
        !zcl_command_registry_input_validate(c->request.spec, &c->input, why,
                                             sizeof(why))) {
        printf("[input rejected: %s] ", why);
        return false;
    }
    handler(&c->request, &c->reply);
    return true;
}

static void fmx_end(struct fmx_call *c)
{
    zcl_command_reply_free(&c->reply);
    json_free(&c->input);
}

static bool fmx_ok(const struct fmx_call *c)
{
    return c->reply.status == ZCL_COMMAND_STATUS_PASSED;
}

static const struct json_value *fmx_get(const struct fmx_call *c,
                                        const char *key)
{
    return json_get(&c->reply.data, key);
}

static const char *fmx_str(const struct fmx_call *c, const char *key)
{
    const struct json_value *v = fmx_get(c, key);
    return v && v->type == JSON_STR && json_get_str(v) ? json_get_str(v) : "";
}

static const struct json_value *fmx_arr(const struct fmx_call *c,
                                        const char *key)
{
    const struct json_value *v = fmx_get(c, key);
    return v && v->type == JSON_ARR ? v : NULL;
}

/* True when missing[] names the given source. */
static bool fmx_missing_has(const struct fmx_call *c, const char *source)
{
    const struct json_value *missing = fmx_arr(c, "missing");
    size_t n, i;
    if (!missing)
        return false;
    n = json_size(missing);
    for (i = 0; i < n; i++) {
        const struct json_value *e = json_at(missing, i);
        const struct json_value *v;
        const char *s;
        if (!e || e->type != JSON_OBJ)
            continue;
        v = json_get(e, "source");
        s = (v && v->type == JSON_STR) ? json_get_str(v) : NULL;
        if (s && strcmp(s, source) == 0)
            return true;
    }
    return false;
}

/* Mint a grant through the real leaf; copies the id out before freeing. */
static bool fmx_mint(const char *scopes, char *id_out, size_t id_cap)
{
    struct fmx_call g;
    const char *id;
    bool ok = false;
    fmx_begin(&g, FMX_GRANT_PATH, "zcl.fleet_mcp_grant.v1");
    (void)json_push_kv_str(&g.input, "action", "mint");
    (void)json_push_kv_str(&g.input, "scopes", scopes);
    if (!fmx_run(&g, zcl_native_handle_fleet_mcp_grant) || !fmx_ok(&g)) {
        fmx_end(&g);
        return false;
    }
    id = fmx_str(&g, "id");
    if (id[0] && strlen(id) == 32 && strlen(id) < id_cap) {
        snprintf(id_out, id_cap, "%s", id);
        ok = true;
    }
    fmx_end(&g);
    return ok;
}

/* One send item object. */
static void fmx_item(struct json_value *item, const char *to,
                     const char *body, const char *ref, const char *key)
{
    json_init(item);
    json_set_object(item);
    (void)json_push_kv_str(item, "to", to);
    (void)json_push_kv_str(item, "body", body);
    (void)json_push_kv_str(item, "ref", ref);
    (void)json_push_kv_str(item, "idempotency_key", key);
}

/* Send one batch through the real leaf. Caller frees items/out. */
static bool fmx_send(struct fmx_call *c, const char *grant,
                     struct json_value *items)
{
    fmx_begin(c, FMX_SEND_PATH, "zcl.fleet_mcp_send.v1");
    if (grant)
        (void)json_push_kv_str(&c->input, "grant", grant);
    (void)json_push_kv(&c->input, "items", items);
    return fmx_run(c, zcl_native_handle_fleet_mcp_send);
}

static void fmx_brief(struct fmx_call *c, const char *grant, long long since)
{
    fmx_begin(c, FMX_BRIEF_PATH, "zcl.fleet_mcp_brief.v1");
    if (grant)
        (void)json_push_kv_str(&c->input, "grant", grant);
    (void)json_push_kv_int(&c->input, "since", since);
}

static void fmx_evidence(struct fmx_call *c, const char *grant,
                         const char *type, const char *ref)
{
    fmx_begin(c, FMX_EVIDENCE_PATH, "zcl.fleet_mcp_evidence.v1");
    if (grant)
        (void)json_push_kv_str(&c->input, "grant", grant);
    (void)json_push_kv_str(&c->input, "type", type);
    (void)json_push_kv_str(&c->input, "ref", ref);
}

/* Mail pull count through the real mail leaf (outbox line accounting
 * without touching paths directly). */
static long long fmx_mail_count(void)
{
    struct fmx_call p;
    long long n = -1;
    json_init(&p.input);
    json_set_object(&p.input);
    memset(&p.request, 0, sizeof(p.request));
    p.request.input = &p.input;
    p.request.spec =
        zcl_command_registry_find(zcl_command_catalog(), "dev.agent.mail",
                                  NULL);
    zcl_command_reply_init(&p.reply, "zcl.agent_mail.v1");
    (void)json_push_kv_str(&p.input, "action", "pull");
    (void)json_push_kv_int(&p.input, "since", 0);
    zcl_native_handle_dev_agent_mail(&p.request, &p.reply);
    if (p.reply.status == ZCL_COMMAND_STATUS_PASSED) {
        const struct json_value *v = json_get(&p.reply.data, "count");
        if (v && v->type == JSON_INT)
            n = json_get_int(v);
    }
    zcl_command_reply_free(&p.reply);
    json_free(&p.input);
    return n;
}

/* Mail ack through the real mail leaf. */
static bool fmx_ack(const char *agent, long long cursor)
{
    struct fmx_call a;
    bool ok;
    json_init(&a.input);
    json_set_object(&a.input);
    memset(&a.request, 0, sizeof(a.request));
    a.request.input = &a.input;
    a.request.spec =
        zcl_command_registry_find(zcl_command_catalog(), "dev.agent.mail",
                                  NULL);
    zcl_command_reply_init(&a.reply, "zcl.agent_mail.v1");
    (void)json_push_kv_str(&a.input, "action", "ack");
    (void)json_push_kv_str(&a.input, "agent", agent);
    (void)json_push_kv_int(&a.input, "cursor", cursor);
    zcl_native_handle_dev_agent_mail(&a.request, &a.reply);
    ok = a.reply.status == ZCL_COMMAND_STATUS_PASSED;
    zcl_command_reply_free(&a.reply);
    json_free(&a.input);
    return ok;
}

/* Seed one queue outcome row so completed-by-ref has evidence to match.
 * The queue status leaf parses this exact reap format. */
static void fmx_seed_outcome(const char *name)
{
    char dir[1024], path[1200];
    int n = snprintf(dir, sizeof(dir), "%s/z23/dev/queue", g_fmx_state);
    if (n <= 0 || (size_t)n >= sizeof(dir))
        fmx_fixture_fail("queue dir exceeds bound");
    if (!platform_private_directory_ensure(dir))
        fmx_fixture_fail("cannot create isolated queue dir");
    n = snprintf(path, sizeof(path), "%s/outcomes.jsonl", dir);
    if (n <= 0 || (size_t)n >= sizeof(path))
        fmx_fixture_fail("outcome path exceeds bound");
    FILE *f = fopen(path, "a");
    if (!f)
        fmx_fixture_fail("cannot seed outcome row");
    /* Writes the reap row shape status parses: name/attempt required,
     * verdict+rc decide pass-like. */
    if (fprintf(f,
                "{\"ts\":\"2026-09-15T00:00:00Z\",\"name\":\"%s\","
                "\"attempt\":1,\"verdict\":\"pass\",\"rc\":0}\n",
                name) < 0)
        fmx_fixture_fail("cannot write outcome row");
    if (fclose(f) != 0)
        fmx_fixture_fail("cannot finish outcome row");
}

/* Craft one expired grant row: expiry honors the wall clock, and no test
 * should sleep to prove it. */
static void fmx_seed_expired(const char *id)
{
    char dir[1024], path[1200];
    int n = snprintf(dir, sizeof(dir), "%s/z23/dev/mcp", g_fmx_state);
    if (n <= 0 || (size_t)n >= sizeof(dir))
        fmx_fixture_fail("mcp dir exceeds bound");
    if (!platform_private_directory_ensure(dir))
        fmx_fixture_fail("cannot create isolated mcp dir");
    n = snprintf(path, sizeof(path), "%s/grants.jsonl", dir);
    if (n <= 0 || (size_t)n >= sizeof(path))
        fmx_fixture_fail("grant path exceeds bound");
    FILE *f = fopen(path, "a");
    if (!f)
        fmx_fixture_fail("cannot seed expired grant");
    if (fprintf(f,
                "{\"id\":\"%s\",\"scopes\":\"brief,send,evidence\","
                "\"created\":1,\"expires\":2,\"revoked\":\"0\","
                "\"label\":\"expired\"}\n",
                id) < 0)
        fmx_fixture_fail("cannot write expired grant");
    if (fclose(f) != 0)
        fmx_fixture_fail("cannot finish expired grant");
}

/* No node in this group, deterministically: every board sibling call
 * fails closed with NODE_UNAVAILABLE instead of depending on ambient
 * ports or cookies. Groups run forked, and the hook is cleared at the
 * single function exit so the sequential runner is unaffected. */
static char *fmx_no_node(const char *method, const char *params_json)
{
    (void)method;
    (void)params_json;
    return NULL;
}

int test_fleet_mcp(void);
int test_fleet_mcp(void)
{
    int failures = 0;

    node_rpc_client_set_test_hook(fmx_no_node);

    TEST("mcp: all four leaves are registered with declared keys") {
        const struct zcl_command_spec *spec =
            zcl_command_registry_find(zcl_command_catalog(), FMX_BRIEF_PATH,
                                      NULL);
        ASSERT(spec != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "since") != NULL);
        spec = zcl_command_registry_find(zcl_command_catalog(),
                                         FMX_SEND_PATH, NULL);
        ASSERT(spec != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "items") != NULL);
        spec = zcl_command_registry_find(zcl_command_catalog(),
                                         FMX_EVIDENCE_PATH, NULL);
        ASSERT(spec != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "ref") != NULL);
        spec = zcl_command_registry_find(zcl_command_catalog(),
                                         FMX_GRANT_PATH, NULL);
        ASSERT(spec != NULL);
        ASSERT(spec->input_keys && strstr(spec->input_keys, "scopes") != NULL);
        PASS();
    }

    TEST("mcp: brief on an empty root reports shape and honest absence") {
        struct fmx_call b;
        fmx_isolate("brief_empty");
        fmx_brief(&b, NULL, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_mcp_brief));
        ASSERT(fmx_ok(&b));
        ASSERT(fmx_arr(&b, "agents") != NULL);
        ASSERT(fmx_arr(&b, "work") != NULL);
        ASSERT(fmx_arr(&b, "blockers") != NULL);
        ASSERT(fmx_arr(&b, "candidates") != NULL);
        ASSERT(fmx_arr(&b, "changes") != NULL);
        ASSERT(fmx_arr(&b, "missing") != NULL);
        ASSERT(json_get(&b.reply.data, "capacity") != NULL);
        ASSERT(json_get(&b.reply.data, "evidence") != NULL);
        /* No node here: the board must be reported missing, never empty. */
        ASSERT(fmx_missing_has(&b, "fleet.board"));
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

    TEST("mcp: mint, send, brief-changes and evidence-by-ref") {
        struct fmx_call s, b, e;
        struct json_value items, item;
        const struct json_value *out, *row;
        char gid[64];
        long long seq;
        fmx_isolate("send_flow");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "field-agent", "sweep the north fence line",
                 "fence-sweep", "key-fence-1");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send(&s, gid, &items));
        json_free(&items);
        ASSERT(fmx_ok(&s));
        out = fmx_arr(&s, "items");
        ASSERT(out != NULL);
        ASSERT_EQ((long long)json_size(out), 1);
        row = json_at(out, 0);
        ASSERT(row != NULL && row->type == JSON_OBJ);
        {
            const struct json_value *v = json_get(row, "state");
            ASSERT(v && v->type == JSON_STR &&
                   strcmp(json_get_str(v), "queued") == 0);
        }
        {
            const struct json_value *v = json_get(row, "seq");
            ASSERT(v && v->type == JSON_INT);
            seq = json_get_int(v);
            ASSERT(seq >= 1);
        }
        {
            const struct json_value *v = json_get(row, "duplicate");
            ASSERT(v && v->type == JSON_BOOL && !json_get_bool(v));
        }
        fmx_end(&s);
        /* The brief carries the directive as a delivered change lead. */
        fmx_brief(&b, gid, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_mcp_brief));
        ASSERT(fmx_ok(&b));
        {
            const struct json_value *changes = fmx_arr(&b, "changes");
            const struct json_value *ch = NULL;
            ASSERT(changes != NULL);
            ASSERT_EQ((long long)json_size(changes), 1);
            ch = json_at(changes, 0);
            ASSERT(ch != NULL && ch->type == JSON_OBJ);
            {
                const struct json_value *v = json_get(ch, "state");
                ASSERT(v && v->type == JSON_STR &&
                       strcmp(json_get_str(v), "delivered") == 0);
            }
            {
                /* Leads, not bodies: the full text stays one call away. */
                const struct json_value *v = json_get(ch, "lead");
                ASSERT(v && v->type == JSON_STR &&
                       strstr(json_get_str(v), "north fence") != NULL);
                v = json_get(ch, "ref");
                ASSERT(v && v->type == JSON_STR &&
                       strcmp(json_get_str(v), "fence-sweep") == 0);
            }
        }
        fmx_end(&b);
        /* Evidence by exact ref returns the whole bounded row. */
        fmx_evidence(&e, gid, "mail", "fence-sweep");
        ASSERT(fmx_run(&e, zcl_native_handle_fleet_mcp_evidence));
        ASSERT(fmx_ok(&e));
        {
            const struct json_value *obj = json_get(&e.reply.data, "object");
            const struct json_value *v;
            ASSERT(obj != NULL && obj->type == JSON_OBJ);
            v = json_get(obj, "body");
            ASSERT(v && v->type == JSON_STR &&
                   strcmp(json_get_str(v), "sweep the north fence line") ==
                       0);
        }
        fmx_end(&e);
        /* Unknown refs are typed refusals, not empty objects. */
        fmx_evidence(&e, gid, "mail", "no-such-ref");
        ASSERT(fmx_run(&e, zcl_native_handle_fleet_mcp_evidence));
        ASSERT(!fmx_ok(&e));
        ASSERT_STR_EQ(e.reply.error.code, "EVIDENCE_NOT_FOUND");
        fmx_end(&e);
        fmx_restore();
        PASS();
    }

    TEST("mcp: duplicate delivery reconciles, never re-posts") {
        struct fmx_call s;
        struct json_value items, item;
        const struct json_value *out, *row;
        const struct json_value *v;
        char gid[64];
        long long before, seq1, seq2;
        fmx_isolate("duplicate");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "field-agent", "check the water pump", "pump-check",
                 "key-pump-1");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send(&s, gid, &items));
        json_free(&items);
        ASSERT(fmx_ok(&s));
        out = fmx_arr(&s, "items");
        ASSERT(out != NULL);
        row = json_at(out, 0);
        v = json_get(row, "seq");
        ASSERT(v && v->type == JSON_INT);
        seq1 = json_get_int(v);
        fmx_end(&s);
        before = fmx_mail_count();
        ASSERT(before == 1);
        /* Same key again: same accept, duplicate flag, no second row. */
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "field-agent", "check the water pump", "pump-check",
                 "key-pump-1");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send(&s, gid, &items));
        json_free(&items);
        ASSERT(fmx_ok(&s));
        out = fmx_arr(&s, "items");
        row = json_at(out, 0);
        v = json_get(row, "seq");
        ASSERT(v && v->type == JSON_INT);
        seq2 = json_get_int(v);
        ASSERT_EQ(seq1, seq2);
        v = json_get(row, "duplicate");
        ASSERT(v && v->type == JSON_BOOL && json_get_bool(v));
        fmx_end(&s);
        ASSERT_EQ(fmx_mail_count(), before);
        /* Oversize batches are refused whole, not truncated. */
        {
            struct fmx_call big;
            struct json_value many, it;
            size_t k;
            json_init(&many);
            json_set_array(&many);
            for (k = 0; k < 9; k++) {
                char kb[32];
                snprintf(kb, sizeof(kb), "key-big-%zu", k);
                fmx_item(&it, "field-agent", "bulk", "", kb);
                (void)json_push_back(&many, &it);
                json_free(&it);
            }
            /* Refused whole at registry validation (bound 8), so the
             * handler never sees a truncated batch. */
            ASSERT(!fmx_send(&big, gid, &many));
            json_free(&many);
            fmx_end(&big);
        }
        fmx_restore();
        PASS();
    }

    TEST("mcp: acknowledged and completed are distinct observed states") {
        struct fmx_call s, b;
        struct json_value items, item;
        const struct json_value *out, *row, *v;
        char gid[64];
        long long seq;
        fmx_isolate("lifecycle");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "rover", "map the crater rim", "crater-rim",
                 "key-crater-1");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send(&s, gid, &items));
        json_free(&items);
        ASSERT(fmx_ok(&s));
        out = fmx_arr(&s, "items");
        row = json_at(out, 0);
        v = json_get(row, "seq");
        ASSERT(v && v->type == JSON_INT);
        seq = json_get_int(v);
        fmx_end(&s);
        /* The receiver acks: the change upgrades to acknowledged. */
        ASSERT(fmx_ack("rover", seq));
        fmx_brief(&b, gid, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_mcp_brief));
        ASSERT(fmx_ok(&b));
        {
            const struct json_value *changes = fmx_arr(&b, "changes");
            const struct json_value *st;
            ASSERT(changes != NULL);
            ASSERT_EQ((long long)json_size(changes), 1);
            st = json_get(json_at(changes, 0), "state");
            ASSERT(st && st->type == JSON_STR &&
                   strcmp(json_get_str(st), "acknowledged") == 0);
        }
        fmx_end(&b);
        /* A pass-like queue outcome on the ref completes it. */
        fmx_seed_outcome("crater-rim");
        fmx_brief(&b, gid, 0);
        ASSERT(fmx_run(&b, zcl_native_handle_fleet_mcp_brief));
        ASSERT(fmx_ok(&b));
        {
            const struct json_value *changes = fmx_arr(&b, "changes");
            const struct json_value *st;
            ASSERT(changes != NULL);
            ASSERT_EQ((long long)json_size(changes), 1);
            st = json_get(json_at(changes, 0), "state");
            ASSERT(st && st->type == JSON_STR &&
                   strcmp(json_get_str(st), "completed") == 0);
        }
        fmx_end(&b);
        fmx_restore();
        PASS();
    }

    TEST("mcp: revoked, unknown, expired and scoped grants fail closed") {
        struct fmx_call c;
        struct json_value items, item;
        char gid[64], narrow[64];
        fmx_isolate("grants");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));
        ASSERT(fmx_mint("send", narrow, sizeof(narrow)));
        /* Narrow scope: brief is outside it. */
        fmx_brief(&c, narrow, 0);
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_mcp_brief));
        ASSERT(!fmx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "MCP_GRANT_SCOPE");
        fmx_end(&c);
        /* Unknown bearer. */
        fmx_brief(&c, "0123456789abcdef0123456789abcdef", 0);
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_mcp_brief));
        ASSERT(!fmx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "MCP_GRANT_UNKNOWN");
        fmx_end(&c);
        /* Revoke: brief and send both refuse, nothing is disguised. */
        fmx_begin(&c, FMX_GRANT_PATH, "zcl.fleet_mcp_grant.v1");
        (void)json_push_kv_str(&c.input, "action", "revoke");
        (void)json_push_kv_str(&c.input, "id", gid);
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_mcp_grant));
        ASSERT(fmx_ok(&c));
        fmx_end(&c);
        fmx_brief(&c, gid, 0);
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_mcp_brief));
        ASSERT(!fmx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "MCP_GRANT_REVOKED");
        fmx_end(&c);
        json_init(&items);
        json_set_array(&items);
        fmx_item(&item, "field-agent", "after revoke", "", "key-rev-1");
        (void)json_push_back(&items, &item);
        json_free(&item);
        ASSERT(fmx_send(&c, gid, &items));
        json_free(&items);
        ASSERT(!fmx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "MCP_GRANT_REVOKED");
        fmx_end(&c);
        /* The revoked send posted nothing. */
        ASSERT_EQ(fmx_mail_count(), 0);
        /* Revoking an unknown id is a refusal, not a silent accept. */
        fmx_begin(&c, FMX_GRANT_PATH, "zcl.fleet_mcp_grant.v1");
        (void)json_push_kv_str(&c.input, "action", "revoke");
        (void)json_push_kv_str(&c.input,
                               "id",
                               "ffffffffffffffffffffffffffffffff");
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_mcp_grant));
        ASSERT(!fmx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "MCP_GRANT_UNKNOWN");
        fmx_end(&c);
        /* Expired rows refuse even with full scope. */
        fmx_seed_expired("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
        fmx_brief(&c, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 0);
        ASSERT(fmx_run(&c, zcl_native_handle_fleet_mcp_brief));
        ASSERT(!fmx_ok(&c));
        ASSERT_STR_EQ(c.reply.error.code, "MCP_GRANT_EXPIRED");
        fmx_end(&c);
        fmx_restore();
        PASS();
    }

    TEST("mcp: board evidence without a node is unavailable, not empty") {
        struct fmx_call e;
        char gid[64];
        fmx_isolate("board_absent");
        ASSERT(fmx_mint("brief,send,evidence", gid, sizeof(gid)));
        fmx_evidence(&e, gid, "board", "deadbeef");
        ASSERT(fmx_run(&e, zcl_native_handle_fleet_mcp_evidence));
        ASSERT(!fmx_ok(&e));
        ASSERT_STR_EQ(e.reply.error.code, "EVIDENCE_UNAVAILABLE");
        fmx_end(&e);
        fmx_restore();
        PASS();
    }

_test_next:;
    node_rpc_client_set_test_hook(NULL);
    fmx_restore();
    if (failures == 0)
        printf("test_fleet_mcp: all passed\n");
    else
        printf("test_fleet_mcp: %d FAILED\n", failures);
    return failures;
}
